dist: bionic
addons:
  apt:
    packages:
      - cmake
language: cpp

git:
  submodules: true

compiler:
#  - clang
  - gcc

before_install:
  - pyenv global 3.7.1

script:
  - mkdir build
  - cd build
  - cmake ..
  - make && ./test_game && PYTHONPATH=${PYTHONPATH}:. python3.7 binding_test.py