dist: bionic
addons:
  apt:
    packages:
      - cmake
language: cpp

git:
  submodules: true

compiler:
  - clang
  - gcc

before_install:
  - pyenv install 3.6.3

script:
  - mkdir build
  - cd build
  - cmake ..
  - make && ./test_game && PYTHONPATH=${PYTHONPATH}:. python binding_test.py